"""Issue #11: breadth-first reachability check for a chosen obstacle-clearance policy.

Checks whether every one of the 24 start/station pairs (3 starts x 8 observe
positions) is reachable on the 4-connected occupancy grid under a given
clearance policy, and reproduces the three findings that motivate the policy
choice: raw grid reachability, uniform one-cell inflation, and selective
inflation at a few radii.
"""

from __future__ import annotations

import sys
from collections import deque
from pathlib import Path

import numpy as np

WEBOTS_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WEBOTS_ROOT.parent
CONTROLLER_DIR = WEBOTS_ROOT / "controllers" / "group_project_controller"

# Use the helpers already supplied with the project. Do not copy the
# conversion or inflation logic into this file.
sys.path.insert(0, str(CONTROLLER_DIR))
from project_utils import CONFIG, apply_clearance_policy, world_to_grid  # noqa: E402

GRID_PATH = WEBOTS_ROOT / "maps" / "occupancy_grid.npy"
REPORT_PATH = REPO_ROOT / "docs" / "decision_clearance.md"

CHOSEN_POLICY = "selective"
CHOSEN_RADIUS = 4
SWEEP_RADII = (1, 2, 3, 4, 5)


def bfs_reachable(grid: np.ndarray, start: tuple[int, int], goal: tuple[int, int]) -> bool:
    """4-connected breadth-first search: is goal reachable from start on free cells?"""
    rows, cols = grid.shape
    if grid[start] == 1 or grid[goal] == 1:
        return False
    if start == goal:
        return True
    visited = {start}
    queue = deque([start])
    while queue:
        row, col = queue.popleft()
        for d_row, d_col in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            n_row, n_col = row + d_row, col + d_col
            if not (0 <= n_row < rows and 0 <= n_col < cols):
                continue
            if grid[n_row, n_col] != 0 or (n_row, n_col) in visited:
                continue
            if (n_row, n_col) == goal:
                return True
            visited.add((n_row, n_col))
            queue.append((n_row, n_col))
    return False


def start_cells() -> list[tuple[str, tuple[int, int]]]:
    cells = []
    for start in CONFIG["starts"]:
        x, y, _ = start["pose"]
        cells.append((start["id"], world_to_grid(x, y)))
    return cells


def station_cells() -> list[tuple[str, tuple[int, int]]]:
    cells = []
    for station in CONFIG["stations"]:
        x, y = station["observe"]
        cells.append((station["id"], world_to_grid(x, y)))
    return cells


def reachability_table(grid: np.ndarray, starts: list, stations: list) -> dict[tuple[str, str], bool]:
    return {
        (s_id, st_id): bfs_reachable(grid, s_cell, st_cell)
        for s_id, s_cell in starts
        for st_id, st_cell in stations
    }


def unreachable_stations(table: dict, stations: list) -> list[str]:
    return [
        st_id
        for st_id, _ in stations
        if not all(table[(s_id, st_id)] for s_id, _ in start_cells())
    ]


def print_table(name: str, table: dict, starts: list, stations: list) -> bool:
    print(f"\n{name}")
    header = "        " + "  ".join(f"{st_id:>4}" for st_id, _ in stations)
    print(header)
    all_ok = True
    for s_id, _ in starts:
        row = []
        for st_id, _ in stations:
            ok = table[(s_id, st_id)]
            all_ok = all_ok and ok
            row.append(f"{'OK' if ok else 'X':>4}")
        print(f"{s_id:>6}  " + "  ".join(row))
    return all_ok


def write_report(
    raw_ok: bool,
    uniform_lost: list[str],
    sweep_results: dict[int, list[str]],
    chosen_table_ok: bool,
) -> None:
    sweep_lines = "\n".join(
        f"- radius {r}: {'all 8 reachable' if not lost else 'still lost: ' + ', '.join(lost)}"
        for r, lost in sweep_results.items()
    )
    report_text = f"""# Decision: Obstacle Clearance Policy

Per [Issue #11](.github/issues/11-obstacle-clearance-strategy.md). Generated by
`python tools/check_reachability.py`; do not hand-edit the numbers below without
re-running it.

## Findings (breadth-first reachability, 4-connected grid, all 3 starts x 8 stations)

1. **Raw grid, no inflation**: {"all 24 start/station pairs reachable" if raw_ok else "NOT all pairs reachable -- unexpected, re-check"}.
2. **Uniform inflation by one cell**: stations lost = {', '.join(uniform_lost) if uniform_lost else 'none'}.
   The interior barriers sit one to two cells apart, so inflating every obstacle by
   one cell seals the corridors into the interior pocket, even though the
   observe cells themselves stay free.
3. **Selective inflation** (inflate by one cell, then restore raw values within a
   Chebyshev radius of each observe cell):
{sweep_lines}

## Decision

Chosen policy: **selective inflation, radius {CHOSEN_RADIUS} cells**, implemented as
`apply_clearance_policy(grid, "selective", observe_cells, radius={CHOSEN_RADIUS})` in
`project_utils.py`. A* (Issue #12) plans on whatever grid this function returns,
so the policy can be swapped later without touching the search.

Chosen policy passes all 24 start/station pairs: **{chosen_table_ok}**.

## Trade accepted

Raw grid gives the most safety margin removed near obstacles far from any
station (full one-cell buffer everywhere it doesn't cost reachability).
Selective inflation gives up that buffer only in the small radius around each
observe cell, where the map's 0.1 m resolution already forces the path close
to a barrier corridor. This leans on [reactive avoidance](.github/issues/14-reactive-avoidance-with-recovery.md)
and the calibrated `WARN`/`STOP` thresholds from
[Issue #4](.github/issues/04-calibrate-proximity-thresholds.md) to catch the
remaining risk, since the occupancy grid is only a 0.1 m approximation of the
real geometry.
"""
    REPORT_PATH.write_text(report_text)


def main() -> int:
    grid = np.load(GRID_PATH)
    starts = start_cells()
    stations = station_cells()

    raw_grid = apply_clearance_policy(grid, "raw")
    raw_table = reachability_table(raw_grid, starts, stations)
    raw_ok = print_table("1. Raw grid, no inflation", raw_table, starts, stations)

    uniform_grid = apply_clearance_policy(grid, "uniform")
    uniform_table = reachability_table(uniform_grid, starts, stations)
    print_table("2. Uniform inflation by one cell", uniform_table, starts, stations)
    uniform_lost = unreachable_stations(uniform_table, stations)
    print(f"Stations lost under uniform inflation: {uniform_lost or 'none'}")

    sweep_results: dict[int, list[str]] = {}
    for radius in SWEEP_RADII:
        sel_grid = apply_clearance_policy(grid, "selective", [c for _, c in stations], radius=radius)
        sel_table = reachability_table(sel_grid, starts, stations)
        lost = unreachable_stations(sel_table, stations)
        sweep_results[radius] = lost
        print_table(f"3. Selective inflation, radius {radius}", sel_table, starts, stations)
        print(f"Stations still lost at radius {radius}: {lost or 'none'}")

    chosen_grid = apply_clearance_policy(grid, CHOSEN_POLICY, [c for _, c in stations], radius=CHOSEN_RADIUS)
    chosen_table = reachability_table(chosen_grid, starts, stations)
    chosen_ok = print_table(
        f"CHOSEN POLICY: {CHOSEN_POLICY} inflation, radius {CHOSEN_RADIUS}", chosen_table, starts, stations
    )

    write_report(raw_ok, uniform_lost, sweep_results, chosen_ok)
    print(f"\nWrote {REPORT_PATH.relative_to(REPO_ROOT)}")

    print(f"\nOVERALL ({CHOSEN_POLICY} radius {CHOSEN_RADIUS}): {'PASS' if chosen_ok else 'FAIL'}")
    return 0 if chosen_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
