"""Issue #7: hand-label the true poster bounding box on a set of real frames.

Run this yourself (not generated by Claude) so the ground truth is an
independent check on find_poster_region(), not something derived from the
same assumptions as the detector.

For each frame: a window opens, zoomed in 5x so the poster is easy to see.
Drag a box tightly around the poster panel (the printed image itself, not
the whole barrier) with the mouse, then press ENTER or SPACE to confirm and
move to the next frame. Press 'c' or ESC to skip a frame with no plausible
poster visible (e.g. a heavily clipped one) -- both behave the same way in
`cv2.selectROI`: an empty selection, recorded as a null box, not a "stop the
whole script" signal. To actually stop early, close the window or Ctrl+C in
the terminal -- results are written to disk after every single frame, so
nothing already labelled is lost.

Resumable: frames already present in the output file (by path) are skipped
on a rerun rather than re-prompted or overwritten, so a partial run (or one
you want to correct a single frame in by deleting its entry first) picks up
where it left off.

Usage:
    python3 tools/label_poster_regions.py

Writes docs/data/poster_region_labels.json: a list of
{"frame": <path>, "box": [x, y, w, h]} at ORIGINAL (not zoomed) pixel
coordinates, or {"frame": <path>, "box": null} for a skipped frame.
"""

from __future__ import annotations

import json
from pathlib import Path

import cv2

WEBOTS_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = WEBOTS_ROOT.parent
FRAME_LIST_PATH = WEBOTS_ROOT / "tools" / "poster_region_label_set.json"
OUT_PATH = REPO_ROOT / "docs" / "data" / "poster_region_labels.json"
ZOOM = 5


def main() -> int:
    frames = json.loads(FRAME_LIST_PATH.read_text())
    results = []
    already_labelled = set()
    if OUT_PATH.exists():
        results = json.loads(OUT_PATH.read_text())
        already_labelled = {row["frame"] for row in results}
        if already_labelled:
            print(f"Resuming: {len(already_labelled)} frame(s) already labelled, skipping those")

    for i, rel_path in enumerate(frames):
        if rel_path in already_labelled:
            continue
        path = REPO_ROOT / rel_path
        img = cv2.imread(str(path))
        if img is None:
            print(f"Could not read {path}, skipping")
            continue
        big = cv2.resize(img, None, fx=ZOOM, fy=ZOOM, interpolation=cv2.INTER_NEAREST)

        window = f"[{i+1}/{len(frames)}] Drag a box around the poster, ENTER to confirm, 'c'/ESC to skip"
        cv2.namedWindow(window, cv2.WINDOW_NORMAL)
        roi = cv2.selectROI(window, big, showCrosshair=True, fromCenter=False)
        cv2.destroyWindow(window)

        x, y, w, h = roi
        if w == 0 or h == 0:
            print(f"{rel_path}: skipped (no box)")
            results.append({"frame": rel_path, "box": None})
        else:
            box = [round(x / ZOOM), round(y / ZOOM), round(w / ZOOM), round(h / ZOOM)]
            print(f"{rel_path}: box={box}")
            results.append({"frame": rel_path, "box": box})

        OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUT_PATH.write_text(json.dumps(results, indent=1))

    print(f"\nSaved {len(results)} labels to {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
